### ISSUE TITLE
Basic functionality

### ISSUE THREAD

**Issue by JulianBlohm** [JulianBlohm/capstone-project#1]
## Value statement -

As a **person**
I need **to know the incidence rate of my area**
so that **I am aware of Covid outdoors**

## Description 
![capstone-project_first-version(2)](https://user-images.githubusercontent.com/68147963/99234892-6e8ae800-27f5-11eb-8a42-f2fed6845b6b.png)

## Acceptance criteria

-   [x] If the user types his area name into the input and clicks the search button, it will show the incidence rate of that area.
-   [x] Input should reset after search
-   [x] Result text updates with new search
-   [x] There is no error message if the area is not found or the API 

## Tasks

-   [x] Create feature Branch
-   [x] Create Inputfield Component
-   [x] Create search Button Component
-   [x] Create RKI API Fetch service
-   [x] Write component tests
-   [x] Add components to app and add text (feature implementation with state)
-   [x] Add missing styles

## Size

large
