### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by JulianBlohm** [JulianBlohm/capstone-project#10]
## Value statement - a requirement, not a solution

As a **user**
I need **to have a nice and clean design **
so that **I can read and access the information easy **

## Description (Text, Scribble, Wireframe, Design)

https://xd.adobe.com/view/c89df4d5-8d65-4355-801d-d6715f4f6cfd-9dce/screen/3d48d075-5afa-4461-898c-dfa266be4e64/specs/

## Acceptance criteria

-   [ ] Good readability
-   [ ] Fast information overview 
-   [ ] Simple and clear functionality

## Tasks

-   [ ] Add icons
-   [ ] Add colors
-   [ ] Add Layout
-   [ ] Test on desktop and mobile

## Size

medium
