### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by JulianBlohm** [JulianBlohm/capstone-project#12]
## Value statement - a requirement, not a solution

As a **developer**
I need **to restrict what the user can do**
so that **nobody can bring the app to stop working properly**

## Description (Text, Scribble, Wireframe, Design)

Validation of input field (form).

## Acceptance criteria

-   [x] If input field is empty Button is disabled.
-   [x] If there is just empty space in the input field, user can't search.
-   [x] It is not possible to submit with more than 32 characters into the input field
-   [x] No special character is allowed, except of "-".
-   [x] Whitespace is trimmed.
-   [x] With the first input a little cross appears to delete the whole input at once.
-   [x] If the input didn't pass the validation, its not removed and there is a message shown

## Tasks

-   [x] Add required to input
-   [x] Add validation logic for input 
-   [x] Add delete cross with logic to input
-   [x] Test on desktop and mobile

## Size

medium
