### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by JulianBlohm** [JulianBlohm/capstone-project#18]
## Value statement 

As a **person**
I need **a nice and clean design**
so that **the information is presented clean and nice.**

## Description (Text, Scribble, Wireframe, Design)

https://xd.adobe.com/view/00595f45-7c17-4b6e-8385-42fa3388b3af-550a/screen/e8247b56-6ffd-4bce-8d4e-673734ea86ed/specs/

## Acceptance criteria

-   [x] Search and result page have the virus icon at the top center
-   [x] Search and result page have the same layout pattern
-   [x] Result page has different colored headings
-   [x] Result page has a new button for a new search
-   [x] Text has different size and weight groups, matching the importance
-   [x] The search button is right next to the input field

## Tasks

-   [x] Layout and structure the pages.
-   [x] Convert all to styled components
-   [x] Import all needed Icons
-   [x] Style, size and position the icons
-   [x] Add correct text
-   [x] Style and position all text
-   [x] Move button next to input and style
-   [x] Create new search button and implement to result page

## Size

large
