### ISSUE TITLE
Geocoding

### ISSUE THREAD

**Issue by JulianBlohm** [JulianBlohm/capstone-project#2]
## Value statement 

As a **person**
I need **to just write my city or postal code**
so that **I can easy get covid-19 information about my county**

## Description (Text, Scribble, Wireframe, Design)

If the user puts the name or the postal code of his city into the search, the geocoding API gives the county back, which is used for the data fetch from the covid-19 RKI API.

![capstone-project_first-version(7)](https://user-images.githubusercontent.com/68147963/99274318-7f098580-282a-11eb-95d1-24d85b4a74a2.png)

## Acceptance criteria

-   [x] Display error feedback if the county search was not successful.
-   [x] Display error feedback if the RKI API fetch was not successful.

## Tasks

-   [x] Create geocoding fetch service
-   [x] Implement fetch and create error handling
-   [x] Test on mobile and desktop

## Size

large
