### ISSUE TITLE
GPS Button 

### ISSUE THREAD

**Issue by JulianBlohm** [JulianBlohm/capstone-project#21]
## Value statement - a requirement, not a solution

As a **person**
I need **the possibility to let the app take my geolocation**
so that **I can easy get information about my geolocation**

## Description (Text, Scribble, Wireframe, Design)
<img width="307" alt="Screenshot 2020-12-08 at 12 51 57" src="https://user-images.githubusercontent.com/68147963/101480608-368a4700-3954-11eb-8da9-59a84aaa8087.png">

## Acceptance criteria

-   [x] The Button has to be right under the input field
-   [x] Should have the same design like the search button of the input (except border radius)
-   [x] It Should have a GPS Icon shown
-   [x] If user clicks, Browser should ask the user if it can use the geolocation.
-   [x] If user applies, it gets geolocation to start the search.
-   [x] If user denied, nothing happens.

## Tasks

-   [x] Create button and import icon
-   [x] Add get geolocation logic
-   [x] Integrate logic in search process
-   [x] Test on mobile and desktop

## Size

medium
