### ISSUE TITLE
Result pages

### ISSUE THREAD

**Issue by JulianBlohm** [JulianBlohm/capstone-project#3]
## Value statement -

As a **person**
I need **the provided information presented clean and clear**
so that **I can orientate and navigate easy and fast**

## Description (Text, Scribble, Wireframe, Design)
![capstone-project_first-version(5)](https://user-images.githubusercontent.com/68147963/99252189-e31e5080-280e-11eb-9bca-33795b8f2b49.png)

## Acceptance criteria

-   [x] At result page name of county and incidence rate are displayed.
-   [x] At result incidence rate greater than 35, the background is red and "...ist ein Covid-19 Hotspot." is shown.
-   [x] At result incidence rate lower than 35, the background is green and "...ist kein Covid-19 Hotspot." is shown.
-   [x] Result Page shows buttons with hyperlink to more informations.
-   [x] If "Neue Suche" Button is clicked, user gets to the main screen and can search again.

## Tasks

-   [x] Create result page 
-   [x] Create result section with rank logic if the place is a covid-19 hotspot or not
-   [x] Create information buttons
-   [x] Create a new search button
-   [x] Add styling

## Size
medium
