### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by JulianBlohm** [JulianBlohm/capstone-project#4]
## Value statement 

As a **person**
I need **to share the result of my county to who ever i want**
so that **other people are easy informed**

## Description (Text, Scribble, Wireframe, Design)

Add router with unique URL paths for the county result page.

## Acceptance criteria

-   [x] If the URL of the result page is shared via copy paste, other user should get the same result page.
-   [x] If the user types a place in the URL the county will be searched and the result page for that county is called.

## Tasks

-   [x] Add react-router
-   [x] Add react-router dynamic URL
-   [x] Add loading logic
-   [x] Test on mobile and desktop

## Size

small
