### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by JulianBlohm** [JulianBlohm/capstone-project#5]
## Value statement 

As a **person**
I need **to know details about the provided informations and how the app works**
so that **I can trust it**

## Description (Text, Scribble, Wireframe, Design)

![capstone-project_first-version(6)](https://user-images.githubusercontent.com/68147963/99260787-2632f080-281c-11eb-9220-b2c1d46a74ee.png)

## Acceptance criteria

-   [x] Questions are shown permanently on main page
-   [x] If the plus icon is clicked, answer should show under question
-   [x] If the plus icon is clicked, there should be a minus icon instead
-   [x] If the minus icon is clicked, answer should hide 
-   [x] If the minus icon is clicked, there should be a plus icon again instead

## Tasks

-   [x] Create FAQ Component
-   [x] Add styling
-   [x] Integrate into app
